import {
  Student,
  Subject,
  Attendance,
  AttendanceRecord,
  Marks,
  Activity,
  Feedback,
  Announcement,
  EventItem,
  TimetableEntry,
  Bus,
  Examination,
  ExamAllocation,
  EndSemesterResult,
} from '../types';

export const SEED_STUDENTS: Student[] = [
  {
    id: '1',
    uid: 'RSET2024CSE001',
    password: 'student123',
    name: 'Brinda Raj',
    class: 'S5 CSE A',
    email: 'rset2024cse001@rajagiri.edu.in',
    phone: '+919847054321',
    gender: 'Female',
    department: 'Computer Science & Engineering',
    semester: 'S5',
    cgpa: '9.42',
    completed_credits: '84',
    photo: '/assets/default_student_avatar.svg',
    signature: 'Brinda Raj',
  },
  {
    id: '2',
    uid: 'RSET2024CSE002',
    password: 'student123',
    name: 'Alan Varghese',
    class: 'S5 CSE A',
    email: 'rset2024cse002@rajagiri.edu.in',
    phone: '+919847112233',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    semester: 'S5',
    cgpa: '8.85',
    completed_credits: '84',
    photo: '/assets/default_student_avatar.svg',
    signature: 'Alan Varghese',
  },
  {
    id: '3',
    uid: 'RSET2024CSE003',
    password: 'student123',
    name: 'Sneha Paul',
    class: 'S5 CSE B',
    email: 'rset2024cse003@rajagiri.edu.in',
    phone: '+919847223344',
    gender: 'Female',
    department: 'Computer Science & Engineering',
    semester: 'S5',
    cgpa: '9.10',
    completed_credits: '84',
    photo: '/assets/default_student_avatar.svg',
    signature: 'Sneha Paul',
  },
  {
    id: '4',
    uid: 'RSET2024CSE004',
    password: 'student123',
    name: 'Rohit Menon',
    class: 'S5 CSE B',
    email: 'rset2024cse004@rajagiri.edu.in',
    phone: '+919847334455',
    gender: 'Male',
    department: 'Computer Science & Engineering',
    semester: 'S5',
    cgpa: '7.12',
    completed_credits: '84',
    photo: '/assets/default_student_avatar.svg',
    signature: 'Rohit Menon',
  },
  {
    id: '5',
    uid: 'RSET2024ECE001',
    password: 'student123',
    name: 'Ananya Nair',
    class: 'S4 ECE A',
    email: 'rset2024ece001@rajagiri.edu.in',
    phone: '+919847445566',
    gender: 'Female',
    department: 'Electronics & Communication',
    semester: 'S4',
    cgpa: '8.65',
    completed_credits: '64',
    photo: '/assets/default_student_avatar.svg',
    signature: 'Ananya Nair',
  },
  {
    id: '6',
    uid: 'RSET2024ECE002',
    password: 'student123',
    name: 'Kevin Joseph',
    class: 'S4 ECE A',
    email: 'rset2024ece002@rajagiri.edu.in',
    phone: '+919847556677',
    gender: 'Male',
    department: 'Electronics & Communication',
    semester: 'S4',
    cgpa: '6.94',
    completed_credits: '64',
    photo: '/assets/default_student_avatar.svg',
    signature: 'Kevin Joseph',
  },
  {
    id: '7',
    uid: 'RSET2024ME001',
    password: 'student123',
    name: 'Rahul Krishnan',
    class: 'S6 ME A',
    email: 'rset2024me001@rajagiri.edu.in',
    phone: '+919847667788',
    gender: 'Male',
    department: 'Mechanical Engineering',
    semester: 'S6',
    cgpa: '8.20',
    completed_credits: '104',
    photo: '/assets/default_student_avatar.svg',
    signature: 'Rahul Krishnan',
  },
  {
    id: '8',
    uid: 'RSET2024IT001',
    password: 'student123',
    name: 'Diya Mathew',
    class: 'S3 IT A',
    email: 'rset2024it001@rajagiri.edu.in',
    phone: '+919847778899',
    gender: 'Female',
    department: 'Information Technology',
    semester: 'S3',
    cgpa: '9.30',
    completed_credits: '44',
    photo: '/assets/default_student_avatar.svg',
    signature: 'Diya Mathew',
  },
];

export const SEED_SUBJECTS: Subject[] = [
  // S5 Subjects
  { id: '1', code: 'CST301', name: 'Formal Languages and Automata Theory', teacher: 'Dr. Elizabeth Isaac', semester: 'S5', credits: '4' },
  { id: '2', code: 'CST303', name: 'Computer Networks', teacher: 'Prof. Jisha G', semester: 'S5', credits: '4' },
  { id: '3', code: 'CST305', name: 'System Software', teacher: 'Prof. Paul Augustine', semester: 'S5', credits: '4' },
  { id: '4', code: 'CST307', name: 'Microprocessors and Microcontrollers', teacher: 'Dr. Ramkumar B', semester: 'S5', credits: '4' },
  { id: '5', code: 'CST309', name: 'Management of Software Systems', teacher: 'Prof. Mary Priya', semester: 'S5', credits: '3' },
  { id: '6', code: 'CSL331', name: 'System Software & Microprocessors Lab', teacher: 'Prof. Paul Augustine', semester: 'S5', credits: '2' },
  // S4 Subjects
  { id: '7', code: 'CST202', name: 'Computer Organization & Architecture', teacher: 'Dr. Anita V', semester: 'S4', credits: '4' },
  { id: '8', code: 'CST204', name: 'Database Management Systems', teacher: 'Prof. Arun Kumar', semester: 'S4', credits: '4' },
  { id: '9', code: 'CST206', name: 'Operating Systems', teacher: 'Dr. Mathew George', semester: 'S4', credits: '4' },
  { id: '10', code: 'EST200', name: 'Design and Engineering', teacher: 'Prof. Shaji K', semester: 'S4', credits: '2' },
  // S3 Subjects
  { id: '11', code: 'MAT203', name: 'Discrete Mathematical Structures', teacher: 'Dr. Vinod P', semester: 'S3', credits: '4' },
  { id: '12', code: 'CST201', name: 'Data Structures', teacher: 'Prof. Neethu Roy', semester: 'S3', credits: '4' },
  { id: '13', code: 'CST203', name: 'Logic System Design', teacher: 'Dr. Bobby Mathew', semester: 'S3', credits: '4' },
];

export const SEED_ATTENDANCE: Attendance[] = [
  // Brinda Raj (S5 CSE A) - High attendance (93%)
  { student_uid: 'RSET2024CSE001', subject_id: '1', present_classes: '36', total_classes: '40', absent_classes: '3', duty_leave_classes: '1', last_updated: '2026-09-05' },
  { student_uid: 'RSET2024CSE001', subject_id: '2', present_classes: '38', total_classes: '42', absent_classes: '2', duty_leave_classes: '2', last_updated: '2026-09-05' },
  { student_uid: 'RSET2024CSE001', subject_id: '3', present_classes: '35', total_classes: '38', absent_classes: '3', duty_leave_classes: '0', last_updated: '2026-09-05' },
  { student_uid: 'RSET2024CSE001', subject_id: '4', present_classes: '34', total_classes: '36', absent_classes: '2', duty_leave_classes: '0', last_updated: '2026-09-05' },
  { student_uid: 'RSET2024CSE001', subject_id: '5', present_classes: '28', total_classes: '30', absent_classes: '2', duty_leave_classes: '0', last_updated: '2026-09-05' },
  { student_uid: 'RSET2024CSE001', subject_id: '6', present_classes: '18', total_classes: '20', absent_classes: '1', duty_leave_classes: '1', last_updated: '2026-09-05' },

  // Alan Varghese (S5 CSE A)
  { student_uid: 'RSET2024CSE002', subject_id: '1', present_classes: '32', total_classes: '40', absent_classes: '7', duty_leave_classes: '1', last_updated: '2026-09-05' },
  { student_uid: 'RSET2024CSE002', subject_id: '2', present_classes: '35', total_classes: '42', absent_classes: '7', duty_leave_classes: '0', last_updated: '2026-09-05' },
  { student_uid: 'RSET2024CSE002', subject_id: '3', present_classes: '32', total_classes: '38', absent_classes: '6', duty_leave_classes: '0', last_updated: '2026-09-05' },

  // Rohit Menon (S5 CSE B) - Low attendance warning (<75%)
  { student_uid: 'RSET2024CSE004', subject_id: '1', present_classes: '25', total_classes: '40', absent_classes: '15', duty_leave_classes: '0', last_updated: '2026-09-05' },
  { student_uid: 'RSET2024CSE004', subject_id: '2', present_classes: '27', total_classes: '42', absent_classes: '15', duty_leave_classes: '0', last_updated: '2026-09-05' },
  { student_uid: 'RSET2024CSE004', subject_id: '3', present_classes: '24', total_classes: '38', absent_classes: '14', duty_leave_classes: '0', last_updated: '2026-09-05' },

  // Sneha Paul
  { student_uid: 'RSET2024CSE003', subject_id: '1', present_classes: '37', total_classes: '40', absent_classes: '3', duty_leave_classes: '0', last_updated: '2026-09-05' },

  // Kevin Joseph - Warning
  { student_uid: 'RSET2024ECE002', subject_id: '7', present_classes: '24', total_classes: '36', absent_classes: '12', duty_leave_classes: '0', last_updated: '2026-09-05' },
];

export const SEED_ATTENDANCE_RECORDS: AttendanceRecord[] = [
  { id: '1', student_uid: 'RSET2024CSE001', subject_id: '1', class: 'S5 CSE A', semester: 'S5', date: '2026-09-01', period: '1', status: 'Present' },
  { id: '2', student_uid: 'RSET2024CSE001', subject_id: '2', class: 'S5 CSE A', semester: 'S5', date: '2026-09-01', period: '2', status: 'Present' },
  { id: '3', student_uid: 'RSET2024CSE001', subject_id: '3', class: 'S5 CSE A', semester: 'S5', date: '2026-09-01', period: '3', status: 'Present' },
  { id: '4', student_uid: 'RSET2024CSE001', subject_id: '4', class: 'S5 CSE A', semester: 'S5', date: '2026-09-02', period: '1', status: 'Duty Leave' },
  { id: '5', student_uid: 'RSET2024CSE001', subject_id: '5', class: 'S5 CSE A', semester: 'S5', date: '2026-09-02', period: '2', status: 'Present' },
  { id: '6', student_uid: 'RSET2024CSE001', subject_id: '1', class: 'S5 CSE A', semester: 'S5', date: '2026-09-03', period: '4', status: 'Present' },
  { id: '7', student_uid: 'RSET2024CSE001', subject_id: '2', class: 'S5 CSE A', semester: 'S5', date: '2026-09-04', period: '2', status: 'Absent' },
  { id: '8', student_uid: 'RSET2024CSE001', subject_id: '3', class: 'S5 CSE A', semester: 'S5', date: '2026-09-04', period: '3', status: 'Present' },
  { id: '9', student_uid: 'RSET2024CSE001', subject_id: '6', class: 'S5 CSE A', semester: 'S5', date: '2026-09-05', period: '5', status: 'Present' },
  { id: '10', student_uid: 'RSET2024CSE001', subject_id: '6', class: 'S5 CSE A', semester: 'S5', date: '2026-09-05', period: '6', status: 'Present' },
];

export const SEED_MARKS: Marks[] = [
  { student_uid: 'RSET2024CSE001', subject_id: '1', internal1: '28', internal2: '29', assignment: '9.5', project: '9.5', max_internal1: '30', max_internal2: '30', max_assignment: '10', max_project: '10' },
  { student_uid: 'RSET2024CSE001', subject_id: '2', internal1: '27', internal2: '28', assignment: '9.0', project: '9.0', max_internal1: '30', max_internal2: '30', max_assignment: '10', max_project: '10' },
  { student_uid: 'RSET2024CSE001', subject_id: '3', internal1: '26', internal2: '27', assignment: '9.0', project: '8.5', max_internal1: '30', max_internal2: '30', max_assignment: '10', max_project: '10' },
  { student_uid: 'RSET2024CSE001', subject_id: '4', internal1: '29', internal2: '28', assignment: '10', project: '9.5', max_internal1: '30', max_internal2: '30', max_assignment: '10', max_project: '10' },
  { student_uid: 'RSET2024CSE001', subject_id: '5', internal1: '25', internal2: '27', assignment: '9.0', project: '9.0', max_internal1: '30', max_internal2: '30', max_assignment: '10', max_project: '10' },
  { student_uid: 'RSET2024CSE001', subject_id: '6', internal1: '29', internal2: '30', assignment: '10', project: '10', max_internal1: '30', max_internal2: '30', max_assignment: '10', max_project: '10' },

  { student_uid: 'RSET2024CSE002', subject_id: '1', internal1: '24', internal2: '25', assignment: '8.5', project: '8.0', max_internal1: '30', max_internal2: '30', max_assignment: '10', max_project: '10' },
  { student_uid: 'RSET2024CSE002', subject_id: '2', internal1: '25', internal2: '26', assignment: '8.5', project: '8.5', max_internal1: '30', max_internal2: '30', max_assignment: '10', max_project: '10' },

  { student_uid: 'RSET2024CSE004', subject_id: '1', internal1: '16', internal2: '18', assignment: '7.0', project: '6.5', max_internal1: '30', max_internal2: '30', max_assignment: '10', max_project: '10' },
  { student_uid: 'RSET2024CSE004', subject_id: '2', internal1: '17', internal2: '16', assignment: '7.0', project: '7.0', max_internal1: '30', max_internal2: '30', max_assignment: '10', max_project: '10' },
];

export const SEED_ACTIVITIES: Activity[] = [
  {
    id: '1',
    student_uid: 'RSET2024CSE001',
    semester: 'S4',
    category: 'Community Service & Volunteering (NSS/NCC)',
    title: 'NSS Kerala Floods Relief Camp Coordinator',
    description: 'Served 40+ hours organizing logistics, distribution, and relief camps.',
    certificate_url: '/uploads/cert_nss_volunteering.pdf',
    points: '20',
    requested_points: '20',
    status: 'Approved',
    remarks: 'Verified 40 hours of volunteer service and official NSS unit report.',
    submitted_at: '2026-06-15',
  },
  {
    id: '2',
    student_uid: 'RSET2024CSE001',
    semester: 'S5',
    category: 'Community Service & Volunteering (NSS/NCC)',
    title: 'National Literacy & Digital Cleanliness Drive',
    description: 'Coordinated student volunteers across 3 local panchayat schools for digital literacy.',
    certificate_url: '/uploads/cert_nss_volunteering.pdf',
    points: '0',
    requested_points: '10',
    status: 'Pending',
    remarks: '',
    submitted_at: '2026-09-02',
  },
  {
    id: '3',
    student_uid: 'RSET2024CSE001',
    semester: 'S4',
    category: 'Sports & Athletics',
    title: 'KTU Interzone Badminton Tournament Winner',
    description: 'Represented RSET in intercollegiate championship winning 1st place in singles.',
    certificate_url: '/uploads/cert_sports_badminton.pdf',
    points: '20',
    requested_points: '20',
    status: 'Approved',
    remarks: 'Physical education department verified medal certificate.',
    submitted_at: '2026-05-18',
  },
  {
    id: '4',
    student_uid: 'RSET2024CSE001',
    semester: 'S5',
    category: 'Cultural & Arts Competitions',
    title: 'Annual Intercollegiate Arts Fest - Classical Music Solo',
    description: 'Secured 1st prize at university level cultural competition in Carnatic vocals.',
    certificate_url: '/uploads/cert_arts_fest.pdf',
    points: '10',
    requested_points: '10',
    status: 'Approved',
    remarks: 'Arts committee verified certificate.',
    submitted_at: '2026-08-05',
  },
  {
    id: '5',
    student_uid: 'RSET2024CSE001',
    semester: 'S4',
    category: 'Internships & Industrial Training',
    title: 'Summer Research Internship at C-DAC',
    description: '4-week industry research internship focusing on high performance computing architectures.',
    certificate_url: '/uploads/cert_cdac_internship.pdf',
    points: '15',
    requested_points: '15',
    status: 'Approved',
    remarks: 'Verified certificate and attendance report.',
    submitted_at: '2026-07-10',
  },
  {
    id: '6',
    student_uid: 'RSET2024CSE001',
    semester: 'S4',
    category: 'Technical Competitions & Hackathons',
    title: 'Smart India Hackathon (SIH) Finalist',
    description: 'National level hackathon problem statement solved using cloud microservices.',
    certificate_url: '/uploads/cert_sih_finalist.pdf',
    points: '10',
    requested_points: '10',
    status: 'Approved',
    remarks: 'Approved by HoD.',
    submitted_at: '2026-07-28',
  },
  {
    id: '7',
    student_uid: 'RSET2024CSE002',
    semester: 'S4',
    category: 'Sports & Athletics',
    title: 'KTU Interzone Badminton Tournament Runner-Up',
    description: 'Represented RSET in intercollegiate championship.',
    certificate_url: '/uploads/cert_sports_badminton.pdf',
    points: '10',
    requested_points: '10',
    status: 'Approved',
    remarks: 'Physical education dept certified.',
    submitted_at: '2026-05-18',
  },
];

export const SEED_FEEDBACK: Feedback[] = [
  {
    id: '1',
    teacher: 'Dr. Elizabeth Isaac',
    subject: 'Formal Languages and Automata Theory',
    subject_code: 'CST301',
    semester: 'S5',
    academic_year: '2026-27',
    q1: '5', q2: '5', q3: '4', q4: '5', q5: '5', q6: '4', q7: '5', q8: '5', q9: '4', q10: '5',
    score: '4.7',
    comments: 'Excellent explanation of Turing machines and Chomsky hierarchy with clear practical examples.',
    submitted_at: '2026-08-25',
  },
  {
    id: '2',
    teacher: 'Prof. Jisha G',
    subject: 'Computer Networks',
    subject_code: 'CST303',
    semester: 'S5',
    academic_year: '2026-27',
    q1: '4', q2: '5', q3: '4', q4: '4', q5: '5', q6: '4', q7: '4', q8: '5', q9: '4', q10: '4',
    score: '4.3',
    comments: 'Packet tracing and Wireshark laboratory sessions were very insightful.',
    submitted_at: '2026-08-26',
  },
];

export const SEED_ANNOUNCEMENTS: Announcement[] = [
  {
    id: '1',
    title: 'End-Semester Examination Registration Notification',
    message: 'Registrations for S5 B.Tech regular and supplementary end-semester examinations are now open on the Rexa portal. Last date without fine: 20th September 2026.',
    date: '2026-09-06',
    category: 'Examination',
    author: 'Controller of Examinations',
  },
  {
    id: '2',
    title: 'KTU Activity Points Verification Deadline',
    message: 'All S5 and S7 students must submit their pending activity certificates and proof documents through RSMS Connect on or before 25th September for faculty advisor approval.',
    date: '2026-09-04',
    category: 'Academic',
    author: 'Dean Academics',
  },
  {
    id: '3',
    title: 'Campus Placement Drive: Google Cloud & Oracle Financial Services',
    message: 'Pre-placement talks and coding assessments for 2026 passing out batch will commence from 15th September. Registered students must carry updated resumes and RSMS Hall Tickets.',
    date: '2026-09-02',
    category: 'Placement',
    author: 'Placement & Training Cell',
  },
  {
    id: '4',
    title: 'Abhiyantriki 2026 - Annual National Tech Fest',
    message: 'Rajagiri national technical fest Abhiyantriki will be held on October 10-12, 2026. Project expo registrations are now live with prizes worth Rs 3,00,000.',
    date: '2026-08-28',
    category: 'Cultural',
    author: 'Student Council',
  },
];

export const SEED_EVENTS: EventItem[] = [
  {
    id: '1',
    title: 'IEEE International Conference on Smart Computing & AI',
    date: '2026-09-18',
    time: '09:30 AM - 04:30 PM',
    venue: 'Kochi Central Auditorium, RSET Campus',
    description: 'Keynotes from leading researchers at Google DeepMind and IISc Bengaluru.',
    category: 'Conference',
  },
  {
    id: '2',
    title: 'Hack@Rajagiri 36-Hour Hackathon',
    date: '2026-09-26',
    time: '08:00 AM Onwards',
    venue: 'PG Block Computing Centre',
    description: 'Build solutions for sustainability, healthtech, and fintech challenges.',
    category: 'Hackathon',
  },
  {
    id: '3',
    title: 'Industry Mentorship Meet with Alumni Leaders',
    date: '2026-10-02',
    time: '02:00 PM - 05:00 PM',
    venue: 'Multimedia Hall 2',
    description: 'One-on-one resume reviews, higher education roadmaps, and career coaching.',
    category: 'Workshop',
  },
];

export const SEED_TIMETABLE: TimetableEntry[] = [
  // Monday
  { id: '1', day: 'Monday', time: '09:00 - 09:55 AM', subject: 'Formal Languages & Automata', room: 'CS-302', teacher: 'Dr. Elizabeth Isaac', class: 'S5 CSE A' },
  { id: '2', day: 'Monday', time: '10:00 - 10:55 AM', subject: 'Computer Networks', room: 'CS-302', teacher: 'Prof. Jisha G', class: 'S5 CSE A' },
  { id: '3', day: 'Monday', time: '11:15 - 12:10 PM', subject: 'System Software', room: 'CS-302', teacher: 'Prof. Paul Augustine', class: 'S5 CSE A' },
  { id: '4', day: 'Monday', time: '01:05 - 02:00 PM', subject: 'Microprocessors & Microcontrollers', room: 'CS-302', teacher: 'Dr. Ramkumar B', class: 'S5 CSE A' },
  { id: '5', day: 'Monday', time: '02:05 - 03:00 PM', subject: 'Management of Software Systems', room: 'CS-302', teacher: 'Prof. Mary Priya', class: 'S5 CSE A' },

  // Tuesday
  { id: '6', day: 'Tuesday', time: '09:00 - 09:55 AM', subject: 'Computer Networks', room: 'CS-302', teacher: 'Prof. Jisha G', class: 'S5 CSE A' },
  { id: '7', day: 'Tuesday', time: '10:00 - 10:55 AM', subject: 'Formal Languages & Automata', room: 'CS-302', teacher: 'Dr. Elizabeth Isaac', class: 'S5 CSE A' },
  { id: '8', day: 'Tuesday', time: '11:15 - 12:10 PM', subject: 'Microprocessors & Microcontrollers', room: 'CS-302', teacher: 'Dr. Ramkumar B', class: 'S5 CSE A' },
  { id: '9', day: 'Tuesday', time: '01:05 - 03:00 PM', subject: 'System Software & Microprocessor Lab', room: 'CS Lab 3', teacher: 'Prof. Paul Augustine', class: 'S5 CSE A' },

  // Wednesday
  { id: '10', day: 'Wednesday', time: '09:00 - 09:55 AM', subject: 'System Software', room: 'CS-302', teacher: 'Prof. Paul Augustine', class: 'S5 CSE A' },
  { id: '11', day: 'Wednesday', time: '10:00 - 10:55 AM', subject: 'Management of Software Systems', room: 'CS-302', teacher: 'Prof. Mary Priya', class: 'S5 CSE A' },
  { id: '12', day: 'Wednesday', time: '11:15 - 12:10 PM', subject: 'Formal Languages & Automata', room: 'CS-302', teacher: 'Dr. Elizabeth Isaac', class: 'S5 CSE A' },
  { id: '13', day: 'Wednesday', time: '01:05 - 02:00 PM', subject: 'Computer Networks', room: 'CS-302', teacher: 'Prof. Jisha G', class: 'S5 CSE A' },

  // Thursday
  { id: '14', day: 'Thursday', time: '09:00 - 09:55 AM', subject: 'Microprocessors & Microcontrollers', room: 'CS-302', teacher: 'Dr. Ramkumar B', class: 'S5 CSE A' },
  { id: '15', day: 'Thursday', time: '10:00 - 10:55 AM', subject: 'System Software', room: 'CS-302', teacher: 'Prof. Paul Augustine', class: 'S5 CSE A' },
  { id: '16', day: 'Thursday', time: '11:15 - 12:10 PM', subject: 'Computer Networks', room: 'CS-302', teacher: 'Prof. Jisha G', class: 'S5 CSE A' },
  { id: '17', day: 'Thursday', time: '01:05 - 03:00 PM', subject: 'Project Lab / Mentoring', room: 'Project Hub 1', teacher: 'Faculty Panel', class: 'S5 CSE A' },

  // Friday
  { id: '18', day: 'Friday', time: '09:00 - 09:55 AM', subject: 'Management of Software Systems', room: 'CS-302', teacher: 'Prof. Mary Priya', class: 'S5 CSE A' },
  { id: '19', day: 'Friday', time: '10:00 - 10:55 AM', subject: 'Microprocessors & Microcontrollers', room: 'CS-302', teacher: 'Dr. Ramkumar B', class: 'S5 CSE A' },
  { id: '20', day: 'Friday', time: '11:15 - 12:10 PM', subject: 'Formal Languages & Automata', room: 'CS-302', teacher: 'Dr. Elizabeth Isaac', class: 'S5 CSE A' },
  { id: '21', day: 'Friday', time: '01:05 - 02:00 PM', subject: 'Technical Seminar Series', room: 'CS Seminar Hall', teacher: 'HOD CS', class: 'S5 CSE A' },
];

export const SEED_BUSES: Bus[] = [
  {
    id: '1',
    bus_no: 'Bus 04',
    route_name: 'Route 1: Aluva - Kalamassery - Collectorate - RSET',
    stops: 'Aluva Metro, Pulinchodu, Companypady, Kalamassery, Premier, Collectorate, Kakkanad, Rajagiri Campus',
    current_stop: 'Collectorate Junction',
    status: 'On Time',
    driver_name: 'Suresh Kumar',
    driver_phone: '+91 94471 23456',
  },
  {
    id: '2',
    bus_no: 'Bus 07',
    route_name: 'Route 2: Vytilla - Palarivattom - Padamugal - RSET',
    stops: 'Vytilla Hub, Chakkaraparambu, Palarivattom Jn, Pipeline, Vazhakkala, Padamugal, Rajagiri Campus',
    current_stop: 'Padamugal',
    status: 'At Stop',
    driver_name: 'George K. A.',
    driver_phone: '+91 94472 34567',
  },
  {
    id: '3',
    bus_no: 'Bus 12',
    route_name: 'Route 3: Tripunithura - Hill Palace - Karingachira - RSET',
    stops: 'Statue Jn, Tripunithura Bus Stand, Hill Palace, Karingachira, Irumpanam, Seaport-Airport Rd, RSET',
    current_stop: 'Karingachira Jn',
    status: 'Delayed',
    driver_name: 'Babu Joseph',
    driver_phone: '+91 94473 45678',
  },
  {
    id: '4',
    bus_no: 'Bus 15',
    route_name: 'Route 4: Angamaly - Athani - Aluva Bypass - RSET',
    stops: 'Angamaly KSRTC, Telk, Athani, Desom, Aluva Bypass, HMT Jn, Rajagiri Campus',
    current_stop: 'Departed Campus',
    status: 'Departed',
    driver_name: 'Antony P.',
    driver_phone: '+91 94474 56789',
  },
  {
    id: '5',
    bus_no: 'Bus 18',
    route_name: 'Route 5: Paravur - Cherai Rd - Varapuzha - RSET',
    stops: 'North Paravur, Koonammavu, Varapuzha Bridge, Cheranalloor, Edappally Toll, RSET',
    current_stop: 'Depot Maintenance',
    status: 'Inactive',
    driver_name: 'Manoj V.',
    driver_phone: '+91 94475 67890',
  },
];

export const SEED_EXAMINATIONS: Examination[] = [
  { id: '1', semester: 'S5', course_code: 'CST301', course_title: 'Formal Languages and Automata Theory', exam_date: '2026-10-14', session_time: '09:30 AM - 12:30 PM', hall_no: 'Exam Hall 401', exam_centre: 'RSET Main Block' },
  { id: '2', semester: 'S5', course_code: 'CST303', course_title: 'Computer Networks', exam_date: '2026-10-17', session_time: '09:30 AM - 12:30 PM', hall_no: 'Exam Hall 401', exam_centre: 'RSET Main Block' },
  { id: '3', semester: 'S5', course_code: 'CST305', course_title: 'System Software', exam_date: '2026-10-21', session_time: '09:30 AM - 12:30 PM', hall_no: 'Exam Hall 402', exam_centre: 'RSET Main Block' },
  { id: '4', semester: 'S5', course_code: 'CST307', course_title: 'Microprocessors and Microcontrollers', exam_date: '2026-10-24', session_time: '09:30 AM - 12:30 PM', hall_no: 'Exam Hall 402', exam_centre: 'RSET Main Block' },
  { id: '5', semester: 'S5', course_code: 'CST309', course_title: 'Management of Software Systems', exam_date: '2026-10-28', session_time: '09:30 AM - 12:30 PM', hall_no: 'Exam Hall 403', exam_centre: 'RSET Main Block' },
];

export const SEED_EXAMS: ExamAllocation[] = [
  { student_uid: 'RSET2024CSE001', exam_name: 'B.Tech S5 Regular Degree Examination Oct 2026', subject: 'Formal Languages and Automata Theory (CST301)', exam_date: '2026-10-14', exam_time: '09:30 AM - 12:30 PM', venue: 'RSET Main Academic Complex', room: 'Hall 401', seat_no: 'A-12' },
  { student_uid: 'RSET2024CSE001', exam_name: 'B.Tech S5 Regular Degree Examination Oct 2026', subject: 'Computer Networks (CST303)', exam_date: '2026-10-17', exam_time: '09:30 AM - 12:30 PM', venue: 'RSET Main Academic Complex', room: 'Hall 401', seat_no: 'A-12' },
  { student_uid: 'RSET2024CSE001', exam_name: 'B.Tech S5 Regular Degree Examination Oct 2026', subject: 'System Software (CST305)', exam_date: '2026-10-21', exam_time: '09:30 AM - 12:30 PM', venue: 'RSET Main Academic Complex', room: 'Hall 402', seat_no: 'B-04' },
  { student_uid: 'RSET2024CSE001', exam_name: 'B.Tech S5 Regular Degree Examination Oct 2026', subject: 'Microprocessors and Microcontrollers (CST307)', exam_date: '2026-10-24', exam_time: '09:30 AM - 12:30 PM', venue: 'RSET Main Academic Complex', room: 'Hall 402', seat_no: 'B-04' },
  { student_uid: 'RSET2024CSE001', exam_name: 'B.Tech S5 Regular Degree Examination Oct 2026', subject: 'Management of Software Systems (CST309)', exam_date: '2026-10-28', exam_time: '09:30 AM - 12:30 PM', venue: 'RSET Main Academic Complex', room: 'Hall 403', seat_no: 'C-08' },
];

export const SEED_END_SEMESTER_RESULTS: EndSemesterResult[] = [
  // S1 Results for Brinda Raj (2024-25)
  { student_uid: 'RSET2024CSE001', semester: 'S1', academic_year: '2024-25', course_code: 'MAT101', course_title: 'Linear Algebra and Calculus', credits: '4', grade: 'O', grade_point: '10', max_marks: '100', marks_obtained: '95', result_status: 'PASS', published_date: '2025-02-15' },
  { student_uid: 'RSET2024CSE001', semester: 'S1', academic_year: '2024-25', course_code: 'PHT100', course_title: 'Engineering Physics A', credits: '4', grade: 'A+', grade_point: '9', max_marks: '100', marks_obtained: '88', result_status: 'PASS', published_date: '2025-02-15' },
  { student_uid: 'RSET2024CSE001', semester: 'S1', academic_year: '2024-25', course_code: 'EST100', course_title: 'Engineering Mechanics', credits: '3', grade: 'A', grade_point: '8.5', max_marks: '100', marks_obtained: '83', result_status: 'PASS', published_date: '2025-02-15' },
  { student_uid: 'RSET2024CSE001', semester: 'S1', academic_year: '2024-25', course_code: 'EST102', course_title: 'Basics of Electrical & Electronics Engineering', credits: '4', grade: 'A+', grade_point: '9', max_marks: '100', marks_obtained: '89', result_status: 'PASS', published_date: '2025-02-15' },
  { student_uid: 'RSET2024CSE001', semester: 'S1', academic_year: '2024-25', course_code: 'HUN101', course_title: 'Life Skills & Professional Communication', credits: '2', grade: 'O', grade_point: '10', max_marks: '100', marks_obtained: '94', result_status: 'PASS', published_date: '2025-02-15' },
  { student_uid: 'RSET2024CSE001', semester: 'S1', academic_year: '2024-25', course_code: 'PHL120', course_title: 'Engineering Physics Lab', credits: '1', grade: 'O', grade_point: '10', max_marks: '100', marks_obtained: '98', result_status: 'PASS', published_date: '2025-02-15' },
  { student_uid: 'RSET2024CSE001', semester: 'S1', academic_year: '2024-25', course_code: 'ESL130', course_title: 'Basics Electrical & Electronics Workshop', credits: '1', grade: 'O', grade_point: '10', max_marks: '100', marks_obtained: '97', result_status: 'PASS', published_date: '2025-02-15' },

  // S2 Results for Brinda Raj (2024-25)
  { student_uid: 'RSET2024CSE001', semester: 'S2', academic_year: '2024-25', course_code: 'MAT102', course_title: 'Vector Calculus, Differential Equations and Transforms', credits: '4', grade: 'O', grade_point: '10', max_marks: '100', marks_obtained: '96', result_status: 'PASS', published_date: '2025-07-20' },
  { student_uid: 'RSET2024CSE001', semester: 'S2', academic_year: '2024-25', course_code: 'CYT100', course_title: 'Engineering Chemistry', credits: '4', grade: 'A+', grade_point: '9', max_marks: '100', marks_obtained: '87', result_status: 'PASS', published_date: '2025-07-20' },
  { student_uid: 'RSET2024CSE001', semester: 'S2', academic_year: '2024-25', course_code: 'EST110', course_title: 'Engineering Graphics', credits: '3', grade: 'A', grade_point: '8.5', max_marks: '100', marks_obtained: '82', result_status: 'PASS', published_date: '2025-07-20' },
  { student_uid: 'RSET2024CSE001', semester: 'S2', academic_year: '2024-25', course_code: 'EST104', course_title: 'Basics of Civil & Mechanical Engineering', credits: '4', grade: 'A+', grade_point: '9', max_marks: '100', marks_obtained: '89', result_status: 'PASS', published_date: '2025-07-20' },
  { student_uid: 'RSET2024CSE001', semester: 'S2', academic_year: '2024-25', course_code: 'EST125', course_title: 'Programming in C', credits: '4', grade: 'O', grade_point: '10', max_marks: '100', marks_obtained: '98', result_status: 'PASS', published_date: '2025-07-20' },
  { student_uid: 'RSET2024CSE001', semester: 'S2', academic_year: '2024-25', course_code: 'CYL120', course_title: 'Engineering Chemistry Lab', credits: '1', grade: 'O', grade_point: '10', max_marks: '100', marks_obtained: '99', result_status: 'PASS', published_date: '2025-07-20' },
  { student_uid: 'RSET2024CSE001', semester: 'S2', academic_year: '2024-25', course_code: 'ESL125', course_title: 'C Programming Lab', credits: '1', grade: 'O', grade_point: '10', max_marks: '100', marks_obtained: '100', result_status: 'PASS', published_date: '2025-07-20' },

  // S3 Results for Brinda Raj (2025-26)
  { student_uid: 'RSET2024CSE001', semester: 'S3', academic_year: '2025-26', course_code: 'MAT203', course_title: 'Discrete Mathematical Structures', credits: '4', grade: 'O', grade_point: '10', max_marks: '100', marks_obtained: '94', result_status: 'PASS', published_date: '2026-02-12' },
  { student_uid: 'RSET2024CSE001', semester: 'S3', academic_year: '2025-26', course_code: 'CST201', course_title: 'Data Structures', credits: '4', grade: 'O', grade_point: '10', max_marks: '100', marks_obtained: '95', result_status: 'PASS', published_date: '2026-02-12' },
  { student_uid: 'RSET2024CSE001', semester: 'S3', academic_year: '2025-26', course_code: 'CST203', course_title: 'Logic System Design', credits: '4', grade: 'A+', grade_point: '9', max_marks: '100', marks_obtained: '88', result_status: 'PASS', published_date: '2026-02-12' },
  { student_uid: 'RSET2024CSE001', semester: 'S3', academic_year: '2025-26', course_code: 'CST205', course_title: 'Object Oriented Programming using Java', credits: '4', grade: 'O', grade_point: '10', max_marks: '100', marks_obtained: '97', result_status: 'PASS', published_date: '2026-02-12' },
  { student_uid: 'RSET2024CSE001', semester: 'S3', academic_year: '2025-26', course_code: 'MCN201', course_title: 'Sustainable Engineering', credits: '2', grade: 'A', grade_point: '8.5', max_marks: '100', marks_obtained: '84', result_status: 'PASS', published_date: '2026-02-12' },
  { student_uid: 'RSET2024CSE001', semester: 'S3', academic_year: '2025-26', course_code: 'CSL201', course_title: 'Data Structures Lab', credits: '2', grade: 'O', grade_point: '10', max_marks: '100', marks_obtained: '99', result_status: 'PASS', published_date: '2026-02-12' },
  { student_uid: 'RSET2024CSE001', semester: 'S3', academic_year: '2025-26', course_code: 'CSL203', course_title: 'Object Oriented Programming Lab', credits: '2', grade: 'O', grade_point: '10', max_marks: '100', marks_obtained: '98', result_status: 'PASS', published_date: '2026-02-12' },

  // S4 Results for Brinda Raj (2025-26)
  { student_uid: 'RSET2024CSE001', semester: 'S4', academic_year: '2025-26', course_code: 'MAT206', course_title: 'Graph Theory', credits: '4', grade: 'A+', grade_point: '9', max_marks: '100', marks_obtained: '89', result_status: 'PASS', published_date: '2026-07-28' },
  { student_uid: 'RSET2024CSE001', semester: 'S4', academic_year: '2025-26', course_code: 'CST202', course_title: 'Computer Organization & Architecture', credits: '4', grade: 'A', grade_point: '8.5', max_marks: '100', marks_obtained: '84', result_status: 'PASS', published_date: '2026-07-28' },
  { student_uid: 'RSET2024CSE001', semester: 'S4', academic_year: '2025-26', course_code: 'CST204', course_title: 'Database Management Systems', credits: '4', grade: 'O', grade_point: '10', max_marks: '100', marks_obtained: '96', result_status: 'PASS', published_date: '2026-07-28' },
  { student_uid: 'RSET2024CSE001', semester: 'S4', academic_year: '2025-26', course_code: 'CST206', course_title: 'Operating Systems', credits: '4', grade: 'A+', grade_point: '9', max_marks: '100', marks_obtained: '88', result_status: 'PASS', published_date: '2026-07-28' },
  { student_uid: 'RSET2024CSE001', semester: 'S4', academic_year: '2025-26', course_code: 'EST200', course_title: 'Design and Engineering', credits: '2', grade: 'A+', grade_point: '9', max_marks: '100', marks_obtained: '90', result_status: 'PASS', published_date: '2026-07-28' },
  { student_uid: 'RSET2024CSE001', semester: 'S4', academic_year: '2025-26', course_code: 'CSL202', course_title: 'Digital Lab', credits: '2', grade: 'O', grade_point: '10', max_marks: '100', marks_obtained: '97', result_status: 'PASS', published_date: '2026-07-28' },
  { student_uid: 'RSET2024CSE001', semester: 'S4', academic_year: '2025-26', course_code: 'CSL204', course_title: 'Database Management Systems Lab', credits: '2', grade: 'O', grade_point: '10', max_marks: '100', marks_obtained: '99', result_status: 'PASS', published_date: '2026-07-28' },

  // S4 Results for Alan Varghese
  { student_uid: 'RSET2024CSE002', semester: 'S4', academic_year: '2025-26', course_code: 'MAT206', course_title: 'Graph Theory', credits: '4', grade: 'A', grade_point: '8.5', max_marks: '100', marks_obtained: '82', result_status: 'PASS', published_date: '2026-07-28' },
  { student_uid: 'RSET2024CSE002', semester: 'S4', academic_year: '2025-26', course_code: 'CST204', course_title: 'Database Management Systems', credits: '4', grade: 'A+', grade_point: '9', max_marks: '100', marks_obtained: '87', result_status: 'PASS', published_date: '2026-07-28' },
  { student_uid: 'RSET2024CSE002', semester: 'S4', academic_year: '2025-26', course_code: 'CST206', course_title: 'Operating Systems', credits: '4', grade: 'B+', grade_point: '8', max_marks: '100', marks_obtained: '78', result_status: 'PASS', published_date: '2026-07-28' },

  // S4 Results for Rohit Menon (with Supplementary)
  { student_uid: 'RSET2024CSE004', semester: 'S4', academic_year: '2025-26', course_code: 'MAT206', course_title: 'Graph Theory', credits: '4', grade: 'F', grade_point: '0', max_marks: '100', marks_obtained: '38', result_status: 'SUPPLEMENTARY', published_date: '2026-07-28' },
  { student_uid: 'RSET2024CSE004', semester: 'S4', academic_year: '2025-26', course_code: 'CST204', course_title: 'Database Management Systems', credits: '4', grade: 'B', grade_point: '7', max_marks: '100', marks_obtained: '68', result_status: 'PASS', published_date: '2026-07-28' },
  { student_uid: 'RSET2024CSE004', semester: 'S4', academic_year: '2025-26', course_code: 'CST206', course_title: 'Operating Systems', credits: '4', grade: 'C', grade_point: '6', max_marks: '100', marks_obtained: '61', result_status: 'PASS', published_date: '2026-07-28' },
];
